find ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour -name "*.png" -type f -delete
find ~/.plexht/addons/skin.aeon.nox.5/media/flags/white -name "*.png" -type f -delete
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/aspectratio/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/audio/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/channels/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/framerate/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/resolution/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/studios/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/au/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/br/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/ca/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/de/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/dm/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/dm/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/fr/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/gb/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/hu/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/hu/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/mpaa/kr/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/135x90/video/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/aspectratio/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/audio/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/channels/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/framerate/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/resolution/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/studios/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/au/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/br/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/ca/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/de -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/dm/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/dm/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/fr/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/gb/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/hu/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/hu/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/mpaa/kr/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/110x60/video/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/aspectratio/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/audio/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/channels/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/framerate/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/resolution/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/studios/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/au/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/br/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/ca/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/de/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/fr/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/gb/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/mpaa/kr/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/110x60/video/ -filter LanczosSharp -distort Resize 110x60 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/clearcases/200x300/ -filter LanczosSharp -distort Resize 200x300\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/clearcases/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/dvd-bluray/200x300/ -filter LanczosSharp -distort Resize 200x300\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/dvd-bluray/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/clearcases/220x330/ -filter LanczosSharp -distort Resize 220x330\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/clearcases/*.*
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/portrait.png -filter LanczosSharp -distort Resize 220x330\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/portrait/glass_220x330.png
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/dvd-bluray/220x330/ -filter LanczosSharp -distort Resize 220x330\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/dvd-bluray/*.*
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/landscape.png -filter LanczosSharp -distort Resize 526x296\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/landscape/glass_526x296.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/landscape.png -filter LanczosSharp -distort Resize 473x266\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/landscape/glass_473x266.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/clearcase.png -filter LanczosSharp -distort Resize 317x317\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/clearcases/clearcase_317x317.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/clearcase.png -filter LanczosSharp -distort Resize 282x282\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/clearcases/clearcase_282x282.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/square.png -filter LanczosSharp -distort Resize 317x317\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/square/glass_317x317.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/square.png -filter LanczosSharp -distort Resize 282x282\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/square/glass_282x282.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/cd.png -filter LanczosSharp -distort Resize 317x317\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/cd/cd_317x317.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/cd.png -filter LanczosSharp -distort Resize 282x282\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/cd/cd_282x282.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/portrait.png -filter LanczosSharp -distort Resize 200x300\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/portrait/glass_200x300.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/portrait.png -filter LanczosSharp -distort Resize 233x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/portrait/glass_233x350.png
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/clearcases/233x350/ -filter LanczosSharp -distort Resize 233x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/clearcases/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/dvd-bluray/233x350/ -filter LanczosSharp -distort Resize 233x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/dvd-bluray/*.*
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/landscape.png -filter LanczosSharp -distort Resize 621x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/landscape/glass_621x350.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/clearcase.png -filter LanczosSharp -distort Resize 350x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/clearcases/clearcase_350x350.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/square.png -filter LanczosSharp -distort Resize 350x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/square/glass_350x350.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/cd.png -filter LanczosSharp -distort Resize 350x350\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/cd/cd_350x350.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/portrait.png -filter LanczosSharp -distort Resize 134x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/portrait/glass_134x200.png
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/clearcases/134x200/ -filter LanczosSharp -distort Resize 134x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/clearcases/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cases/dvd-bluray/134x200/ -filter LanczosSharp -distort Resize 134x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cases/dvd-bluray/*.*
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/landscape.png -filter LanczosSharp -distort Resize 300x169\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/landscape/glass_300x169.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/clearcase.png -filter LanczosSharp -distort Resize 200x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/clearcases/clearcase_200x200.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/cd/cd.png -filter LanczosSharp -distort Resize 200x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/cd/cd/cd_200x200.png
convert ~/Pictures/skin.aeon.nox.5.images.master/cases/glass/square.png -filter LanczosSharp -distort Resize 200x200\! -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/.plexht/addons/skin.aeon.nox.5/media/cases/glass/square/glass_200x200.png
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/aspectratio/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/audio/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/channels/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/framerate/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/resolution/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/studios/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/au/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/br/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/ca/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/de -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/fr/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/gb/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/mpaa/kr/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/135x90/video/ -filter LanczosSharp -distort Resize 135x90 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x115/studios/ -filter LanczosSharp -distort Resize 140x115 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x115/studios/ -filter LanczosSharp -distort Resize 140x115 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/au/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/br/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/ca/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/de/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/dm/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/dm/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/fr/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/gb/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/hu/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/hu/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/mpaa/kr/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/au/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/br/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/ca/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/de/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/fr/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/gb/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/mpaa/kr/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/resolution/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/resolution/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/video/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/video/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/120x65/audio/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/120x65/audio/ -filter LanczosSharp -distort Resize 120x65 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/75x55/channels/ -filter LanczosSharp -distort Resize 75x55 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/75x55/channels/ -filter LanczosSharp -distort Resize 75x55 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/118x80/resolution/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/118x80/resolution/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/118x80/video/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/118x80/video/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/118x80/audio/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/118x80/audio/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/118x80/channels/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/118x80/channels/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/cdart/source/47x47/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/cdart/source/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/118x80/channels/ -filter LanczosSharp -distort Resize 118x80 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/audio/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/channels/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/au/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/br/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/ca/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/de/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/fr/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/gb/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/mpaa/kr/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/47x47/studios/ -filter LanczosSharp -distort Resize 47x47 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/aspectratio/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/audio/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/channels/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/framerate/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/resolution/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/studios/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/au/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/br/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/ca/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/de/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/dm/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/dm/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/fr/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/gb/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/hu/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/hu/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/mpaa/kr/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/140x95/video/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/video/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/video/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/aspectratio/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/aspectratio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/audio/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/audio/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/channels/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/channels/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/framerate/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/framerate/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/resolution/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/studios/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/studios/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/au/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/br/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/ca/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/de/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/fr/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/gb/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/140x95/mpaa/kr/ -filter LanczosSharp -distort Resize 140x95 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/au/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/br/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/ca/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/de/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/dm/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/dm/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/fr/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/gb/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/hu -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/hu/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/mpaa/kr/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/au/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/au/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/br/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/br/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/ca/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/ca/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/de/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/de/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/fr/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/fr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/gb/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/gb/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/mpaa/kr/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/mpaa/kr/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/colour/240x240/resolution/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/coloured/resolution/*.*
mogrify -path ~/.plexht/addons/skin.aeon.nox.5/media/flags/white/240x240/resolution/ -filter LanczosSharp -distort Resize 240x240 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB ~/Pictures/skin.aeon.nox.5.images.master/flags/white/resolution/*.*
